### ISSUE TITLE
IMAP Mail UID

### ISSUE THREAD

**Issue by krytyYT** [umanamente/n8n-nodes-imap#7]
Hi, when i use IMAP receiving block in n8n there is no email uid included from what i can see. Is there anyway to get this email uid so i can manipulate emails with this module?

**Comment by umanamente** [comment]
Unfortunately there is currently no way to connect N8N builtin IMAP trigger node and this node, because N8N node doesn't return UID, which is used to retrieve specific emails.
It does return "Message-ID", but it is not guaranteed for IMAP servers to support fetching emails by this property.

Available options are:
1. Request the N8N development team to include UID information in the output of the IMAP trigger node. This change would allow for direct integration with this node.
2. Alternatively, you can bypass the IMAP trigger node and instead set up a periodic trigger to fetch new messages from the IMAP server at regular intervals (e.g., every minute).
